### ISSUE TITLE
3.11.2 rhel image uses Management Center 3.11.1

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/management-center-openshift#8]
I have verified that 3.11.2 rhel image uses Management Center 3.11.1 but `registry.connect.redhat.com/hazelcast/management-center-3-rhel7:3.11.3` seems correct. We need to check release process and see what caused that anomaly. cc: @emre-aydin @hasancelik

**Comment by emre-aydin** [comment]
You put the MC version manually to the Jenkins build before starting the release. It's easy enough but human errors are inevitable I guess. To automate it completely, I can make the MC release script to trigger the openshift build via Jenkin's REST API. Need to check if it's possible though.

**Comment by leszko** [comment]
Just a note from my side: the release is always done from `master`, so you need to update `master` with the correct version and only then run the Jenkins pipeline.

**Comment by mesutcelik** [comment]
Thanks Guys, I think What Emre suggests is very good solution and save some manual operations from post release actions... cc: @Holmistr

**Comment by Holmistr** [comment]
Guys, it's possible that I've made the mistake. Could you please review the "How to release Hazelcast" page and update the post release actions, so they are up to date? I always go step by step with this document.

**Comment by Holmistr** [comment]
And yes, I'm really looking to the day, when I have time to automate all this :)

**Comment by leszko** [comment]
@Holmistr , I've added one point to "How to release Hazelcast". Saying that, I think we never had issues with Hazelcast RHEL release. This issue is related to MC. @emre-aydin, could you check that the Management Center Release steps are up to date?
